### ISSUE TITLE
Création d'un nouveau jeu

### ISSUE THREAD

**Issue by chcourtin** [ludomuse/LudoMuseEditor#14]
Si on veut créer un nouveau jeu, on ne sait pas qui est le grand et qui est le petit… comment le faire simplement ?

**Comment by Babouchot** [comment]
le premier joueur (à gauche sur l'écran de choix du personnage) a ses écrans en haut de la timeline.
le second (à droite) a ses écran en bas de la timeline.
De même dans l'utilitaire d'ajout de scène le premier joueur est à gauche et le second à droite.
