### ISSUE TITLE
plantage lors de la création de nouvelles scènes

### ISSUE THREAD

**Issue by chcourtin** [ludomuse/LudoMuseEditor#9]
Plantage régulier : J’ai diminué la taille des images, et je veux déplacer le screen-reward2 qui est mal placé dans le scénario. Je le supprime (supprimer scène), puis je fais nouvelle scène après scren-2-g-player1, je fais nouvelle scène, en prenant le modèle écran de récompense. Il me demande de créer une scène id, je l’intitule recompense2. Je valide et me retrouve avec l’image jointe. Si je clique sur une partie de l’écran (texte par exemple pour le modifier ou le fond pour changer le background) l’appli plante. Vérification faite, c’est que je n’utilise pas la bonne ID en l’occurrence screen-reward2. Mais comme je ne sais pas où on les détermine, c’est un peu bloquant

**Comment by Babouchot** [comment]
Le correctif n'est pas encore publié sur la version MacOS mais devrait arriver dans un mise à jour prochaine.
